name: Deploy Vite React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Prepare SSH Key for Deployment
      - name: Prepare SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          printf "%s" "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

      # Step 2: Deploy to server
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "78.141.243.243"
          REMOTE_USER: "root"  # Replace with your actual username if not root
          TARGET: "/var/www/MiManager_project_management/dist"
